UpCloudLtd/upcloud-go-api

upcloud/storage.go
upcloud/storage_test.go

Hello there,
I recently noticed that there is no Backups fields in the StorageDetails{} and that it was a TODO that was never done :) . We require it in my company to be able to have the array of backups UUIDs when we are requesting information regarding the details of a storage device. 
What is done in these commits:
- Added BackupUUIDs as an array of strings (follows the convention naming set by ServerUUIDs)
- Added a constant for the normal storage type
- Rearranged the StorageType constants by alphabetical order
- Added a test to unmarshal a StorageDetails struct

Field Backups was added to StorageDetails struct

---

upcloud/service/service_test.go
upcloud/storage.go
upcloud/storage_test.go

Should fix #45. Let me know if any changes are needed.

Support fields "created" and "origin" for backup storages

---

upcloud/client/client.go
upcloud/service/service.go

* client: only set default timeout if the caller hasn't provieded a HTTP
client with non-zero timeout.
* service: restore timeout in server start and stop while allowing additional
time for the API to respond with an error.

client/service: better timeout handling

---

upcloud/client/client.go
upcloud/request/storage.go
upcloud/service/storage.go

* request: SourceLocation is now untyped to allow passing of io.Reader
instead of just string. This gives caller more flexibility
while still providing ease of use. A new ContentType field
allows the caller to specify if the locally available image
is compressed or not.
* service: support io.Reader by type asserting the SourceLocation.
If it's string then it's used as a file name. Otherwise the
io.Reader is passed as-is. Content type is set according
to the request.
* client:  support setting and getting of content type. Use the Set
method instead of Add to reset the specified headers.

Storage import ioreader

---

upcloud/request/server.go
upcloud/storage.go
upcloud/storage_test.go

* request: set SSHKeys to omitempty as the field is optional and will
otherwise get validated by the API.
* upcloud: fix StorageImportDetails.Completed field decoding. Use an alias
struct and separately parse the completed timestamp if it's not
an empty string. Also expose SourceLocation which is provided
by the API.

fix server and storage import related type encoding/decoding

---

upcloud/request/server.go

size is optional (defaulting to the size of the original) when cloning a storage
terraform provider allows omitting size for storage when creating a new one with clone action (throwing an error, as not supported by the sdk).

fix: omitempty on CreateServerStorageDevice

---

upcloud/account.go
upcloud/account_test.go

unlimited resources were displayed as zero values (0) which was confusing

fix: add omitempty for fields in account resourcelimits

---

upcloud/storage.go

the only way to delete the backup rule is to pass backup_rule: {} to the modify storage request. Currently this is not possible with the go api

fix: backup_rule deletion

---

upcloud/service/service_test.go
upcloud/service/storage_test.go
upcloud/service/utils_test.go

It seems like some tests that should be skipped with -short weren't, which is fixed with this PR.
This includes *all* tests using record(), as they all seem to require credentials to be set. (?)

Test: fix -short in tests

---

upcloud/request/network.go
upcloud/request/network_test.go
upcloud/service/fixtures/createtwonetworkstwoserversandarouter.yaml
upcloud/service/network.go
upcloud/service/network_test.go
upcloud/service/utils_test.go

BREAKING CHANGE: This PR will break backwards compatibility so after merging, merge #91 and release 4.0.0
- Remove the old 'Router' field from ModifyNetworkRequest, as it was unsalvageable in it's current form and I feel it's better to remove altogether to force former users to use the new approach
- Implement AttachNetworkRouter and DetachNetworkRouter (and related request types) that actually work
- fixes a network related test and updates it's fixtures

Fix(network): implement router attach/detach

---

.github/workflows/lint.yml
upcloud/service/storage_test.go

Fixes `File creation in shared tmp directory without using ioutil.Tempfile (gosec)` linting error

fix(test): use ioutil.Tempfile in storage test

---

CHANGELOG.md
README.md
upcloud/client/client.go
upcloud/client/client_test.go

Add new env debug flag `UPCLOUD_DEBUG_API_BASE_URL` to customize API base URL.

feat(client): new debug flag for setting custom base URL

---

CHANGELOG.md
upcloud/request/managed_database.go
upcloud/request/managed_database_test.go

Fixes maintenance property not sent if either time or dow is empty
when creating database.

fix(dbaas) maintenance window empty values

---

CHANGELOG.md
upcloud/firewall.go
upcloud/request/firewall_test.go
upcloud/service/firewall_test.go
upcloud/service/fixtures/firewallrules.yaml

Omit empty IP address family from firewall rule request so that default
rules can be created without family field.

fix(firewall): drop IP address family requirement

---

upcloud/client/client.go
upcloud/client/client_ctx.go
upcloud/client/client_ctx_test.go
upcloud/client/client_test.go

Disable default timeout when using context aware client
as it might result in unexpected behaviour when using context cancellation.

feat(client-context): disable default timeout

---

upcloud/server.go
upcloud/server_test.go

Add constants for NIC models as defined in [the API spec](https://developers.upcloud.com/1.3/8-servers/#attributes).

chore(server): add constants for NIC models

---

upcloud/request/server.go
upcloud/request/server_test.go

Add `nic_model` parameter to create and modify server requests. Already present in `ServerDetails`. This will allow clients to define a custom `nic_model` upon server creation or modification.

chore(server): add NIC model attribute to server related calls

---

upcloud/load_balancer.go
upcloud/load_balancer_test.go
upcloud/service/fixtures/loadbalancer.yaml
upcloud/service/fixtures/loadbalancerbackend.yaml
upcloud/service/fixtures/loadbalancerbackendmember.yaml
upcloud/service/fixtures/loadbalancercerticatebundlesandfrontendtlsconfigs.yaml
upcloud/service/fixtures/loadbalancerfrontend.yaml
upcloud/service/fixtures/loadbalancerfrontendrule.yaml
upcloud/service/fixtures/loadbalancerlabels.yaml
upcloud/service/fixtures/loadbalancernetworks.yaml
upcloud/service/fixtures/loadbalancerpage.yaml
upcloud/service/fixtures/loadbalancerresolver.yaml
upcloud/service/load_balancer_test.go

- Add support for LB backend member property `health_check_tls_verify`. If enabled, no TLS certificate validation is done for backend members that are using `https` scheme for health checks.
- Fix LB service tests.
- Use valid CIDR ranges.
- Change `t.Cleanup()` to `defer` to match how other tests are handling cleanup. Worth noting that `t.Cleanup()` does not work as recorder cancels the test `ctx` as soon as the test has concluded.
- LB `DELETE` calls were present in fixtures but they were explicitly being passed through by the recorder. Now fixtures and tests are aligned.
- Update LB fixtures.

feat(lbaas): support for controlling health check TLS verify

---

CHANGELOG.md
go.mod
go.sum
upcloud/client/client.go
upcloud/service/utils_test.go

This replaces  `go-cleanhttp`  dependency with `NewDefaultHTTPClient` and `NewDefaultHTTPTransport` functions. Functions are exported so that client and/or transport can be easily modified by user if needed. 
HTTP client properties should be identical to what was previously, except for `ForceAttemptHTTP2`, which is also set in latest `go-cleanhttp` package.

refactor(client): new http.Client init function

---

.github/workflows/lint.yml
.github/workflows/test.yml
.golangci.yaml
Makefile
go.mod

- Use Go 1.19 in `go.mod` and CI actions
- Test against two previous Go major releases (1.19, 1.20) and drop out 1.18
- Remove deprecated linters
- Add make command for `lint` :)

chore: use Go 1.19

---

CHANGELOG.md
upcloud/service/kubernetes.go

Sleep before `GET` request in `WaitForKubernetesClusterState` to avoid getting stale state in some scenarios. This will also align function behavior with other services.

fix(kubernetes): sleep before `GET` request in `WaitForKubernetesClusterState`

---

CHANGELOG.md
README.md
examples/upcloud-cli/main.go
upcloud/request/kubernetes.go
upcloud/request/managed_database.go
upcloud/request/managed_object_storage.go
upcloud/request/server.go
upcloud/request/storage.go
upcloud/service/kubernetes.go
upcloud/service/kubernetes_test.go
upcloud/service/managed_database.go
upcloud/service/managed_database_test.go
upcloud/service/managed_object_storage.go
upcloud/service/managed_object_storage_test.go
upcloud/service/retry.go
upcloud/service/retry_test.go
upcloud/service/server.go
upcloud/service/server_test.go
upcloud/service/storage.go
upcloud/service/storage_test.go
upcloud/service/utils_test.go

This is to remove duplicate timeouts: the `context.Context` parameter passed in to the `WaitFor*` methods might already have an timeout defined. Thus, the `Timeout` field might cause confusing errors when, for example, the timeout defined in `Timeout` field is shorter than timeout defined in the context passed in from e.g. Terraform.

refactor: remove `Timeout` option from `WaitFor*` methods

---

CHANGELOG.md
upcloud/request/gateway.go
upcloud/request/gateway_test.go

This reverts commit bb108795ee029e8cd3f3882fcb3e80a96fc4cf87. The `GetGateways` method already supports paging as `*Page` implements `QueryFilter` interface. Thus this change is not needed for now. This can be re-done later if we want to sync service methods so that all list methods take the related request struct as a parameter.

chore(gateway): revert adding `Page` field to `GetGatewaysRequest`

---

upcloud/account.go
upcloud/account_test.go
upcloud/request/account.go
upcloud/request/account_test.go
upcloud/service/account.go

This PR adds billing summary support to the account service.
Follows the API /account/billing/summary/{year-month} endpoint as documented in the account section.
Notes:
-  The `BillingCategory` and `BillingResourceGroup` structs handle the nested JSON structure where categories contain both a total_amount and a nested object (e.g., servers.server, managed_databases.managed_database). If there is a better approach, let me know.
- Some billing categories like `storages` and `networks` are not included as they require specific API response examples. If you can provide with that details, I can implement.

feat(account): add billing summary

---

CHANGELOG.md
upcloud/account.go
upcloud/account_test.go
upcloud/plan.go
upcloud/plan_test.go
upcloud/service/account_test.go

- Add GPUs field to ResourceLimits struct for account resource limits
- Add GPUAmount and GPUModel fields to Plan struct for server plans
- Update tests to include GPU field validation

feat: add GPUs to resource limits and server plans

---

.github/workflows/test.yml
CHANGELOG.md
go.mod

As per [Go release policy](https://go.dev/doc/devel/release#policy), Go 1.23 is no longer supported.

chore(deps): bump Go version to v1.24

---

CHANGELOG.md
upcloud/network.go
upcloud/request/network_test.go
upcloud/service/fixtures/dhcpnetworkconfigurations.yaml
upcloud/service/network_test.go

This is needed to be able to clean dhcp filters from the terraform provider. 
nil pointer array -> not specified, keep what you have
pointer to empty array -> clean the values
pointer to array -> Set the values

chore(net dhcp): convert to pointer
