UpCloudLtd/upcloud-go-api

upcloud/request/server.go, upcloud/request/server_test.go, upcloud/service/service.go, upcloud/service/service_test.go
Should fix #43. Let me know if any changes are needed.
=> Support deletion of servers including all attached storages, fixes #43

upcloud/storage.go
Changes:
* Add 'syncing' storage state constant
=> Add "syncing" storage state

go.sum, upcloud/client/client.go, upcloud/object_storage.go, upcloud/object_storage_test.go, upcloud/request/object_storage.go, upcloud/request/object_storage_test.go, upcloud/service/fixtures/getobjectstoragedetails.yaml, upcloud/service/fixtures/getobjectstorages.yaml, upcloud/service/object_storage.go, upcloud/service/object_storage_test.go, upcloud/service/utils_test.go
This PR adds all CRUD operations for Object Storage.
API: https://developers.upcloud.com/1.3/15-object-storage/
=> Object storage

upcloud/client/client.go, upcloud/service/storage.go
- set different content-type on request level
- expose method for dispatching request object
=> refactor: do not set contenttype for client

internal/globals.go, upcloud/client/client.go
feature: expose UserAgent -field which will be passed as a header for requests
=> user-agent

upcloud/service/network.go, upcloud/service/service.go
Couple of interfaces got missed out of the original PR: 
* Routers from Networking
* Account
* Price zones
* Time zones
* Plan
=> Add missing interfaces

upcloud/server_test.go, upcloud/storage.go
tier is now added to the payload received from the api
=> chore: add tier to ServerStorageDevice

CHANGELOG.md, README.md, internal/globals.go
- update README and CHANGELOG for 4.0.0
- waiting for #90 to be merged first
=> Chore: release 4.0.0

.github/workflows/lint.yml, .github/workflows/test.yml
Signed-off-by: Amine Kherbouche <kaminek92@gmail.com>
=> chore(ci): prevent running lint twice foreach go version

.golangci.yaml, upcloud/client/client.go, upcloud/service/fixtures/getnetworksinzone.yaml, upcloud/service/network_test.go, upcloud/service/object_storage.go, upcloud/service/service.go, upcloud/service/service_test.go, upcloud/service/storage.go, upcloud/service/storage_test.go, upcloud/service/utils_test.go
This MR re-enables the few linters that were disabled previously and fixes relevant linting warnings.
=> chore: re-enable linters

upcloud/account.go, upcloud/account_test.go, upcloud/request/account.go, upcloud/request/account_test.go, upcloud/service/account.go, upcloud/service/account_test.go, upcloud/service/fixtures/createmodifydeletesubaccount.yaml, upcloud/service/service.go
Implement subaccount CRUD operations and account listing.
=> feat(account): Subaccount management

upcloud/load_balancer.go, upcloud/load_balancer_test.go, upcloud/request/load_balancer.go, upcloud/service/load_balancer.go, upcloud/service/load_balancer_test.go, upcloud/service/utils_test.go
- rename LB types
- add LoadbalancerPlan type
=> chore(lbaas): rename LB types

upcloud/service/fixtures/createmodifydeleteloadbalancerbackend.yaml, upcloud/service/fixtures/createmodifydeleteloadbalancerbackendmember.yaml, upcloud/service/fixtures/getloadbalancerbackenddetails.yaml, upcloud/service/fixtures/getloadbalancerbackendmemberdetails.yaml, upcloud/service/fixtures/getloadbalancerbackendmembers.yaml, upcloud/service/fixtures/getloadbalancerbackends.yaml
just removing some unnecessary stuff from fixtures 😁
=> fix(loadbalancer): remove unnecessary header from fixtures

upcloud/load_balancer.go, upcloud/load_balancer_test.go, upcloud/service/load_balancer_test.go, upcloud/service/utils_test.go
- update load balancer tests
- add missing types/consts
- fix typos
=> chore(lbaas): load balancer tests

upcloud/load_balancer.go, upcloud/load_balancer_test.go
- add type comments
- rename LoadBalancerRule to LoadBalancerFrontendRule
=> chore(lbaas): add type comments

upcloud/client/client.go, upcloud/client/error.go, upcloud/problem.go, upcloud/problem_test.go, upcloud/request/load_balancer.go, upcloud/request/load_balancer_test.go, upcloud/service/fixtures/getloadbalancerplans.yaml, upcloud/service/fixtures/loadbalancer.yaml, upcloud/service/fixtures/loadbalancerbackend.yaml, upcloud/service/fixtures/loadbalancerbackendmember.yaml, upcloud/service/fixtures/loadbalancerfrontend.yaml, upcloud/service/fixtures/loadbalancerresolver.yaml, upcloud/service/load_balancer.go, upcloud/service/load_balancer_test.go, upcloud/service/service.go, upcloud/service/utils_test.go
- add LB frontend service and request types
- add new Problem type to handle problem responses
- rename recordings
=> feat(lbaas): load balancer frontends

upcloud/request/load_balancer.go, upcloud/request/load_balancer_test.go
Include 'enabled' field to JSON also when it's set to false
=> fix(lbaas) backend member enabled flag

upcloud/request/load_balancer.go, upcloud/request/load_balancer_test.go
Remove "omitempty" tag from fields 'weight' and 'max_session' because those can have zero values
=> fix(lbaas): handle BE member zero values

upcloud/request/load_balancer.go
Remove omitempty from frontend rule required fields.
=> fix(lbaas): frontend rule required fields

upcloud/request/load_balancer.go, upcloud/request/load_balancer_test.go
Remove key_type from "Modify dynamic certificate bundle" request.
=> fix(lbaas): fix certificate bundle mod request

upcloud/request/load_balancer.go, upcloud/request/load_balancer_helpers.go, upcloud/request/load_balancer_test.go, upcloud/service/fixtures/loadbalancer.yaml, upcloud/service/fixtures/loadbalancerbackend.yaml, upcloud/service/fixtures/loadbalancerbackendmember.yaml, upcloud/service/fixtures/loadbalancercerticatebundlesandfrontendtlsconfigs.yaml, upcloud/service/fixtures/loadbalancerfrontend.yaml, upcloud/service/fixtures/loadbalancerfrontendrule.yaml, upcloud/service/fixtures/loadbalancerresolver.yaml
- add helper functions to create request types
- update load balancer request to use new URL
=> feat(lbaas): add request helpers

upcloud/client/client.go
Add new env debug flag `UPCLOUD_DEBUG_SKIP_CERTIFICATE_VERIFY` to skip certificate verification
=> feat(client): new debug flag

upcloud/request/load_balancer_helpers.go, upcloud/request/load_balancer_helpers_test.go
Add request helper tests and change `ignoreCase` boolean parameter to
boolean pointer to allow field exclusion from JSON.
=> chore(lbaas): add request helper tests

.github/workflows/lint.yml, upcloud/request/load_balancer.go, upcloud/request/load_balancer_test.go, upcloud/service/fixtures/getloadbalancerplans.yaml, upcloud/service/load_balancer.go, upcloud/service/load_balancer_test.go
Support for limit and offset query parameters when listing load balancers plans.
=> feat(lbaas): load balancer plan paging

upcloud/request/load_balancer.go, upcloud/request/load_balancer_test.go, upcloud/service/fixtures/loadbalancercerticatebundlesandfrontendtlsconfigs.yaml, upcloud/service/load_balancer.go, upcloud/service/load_balancer_test.go
Support for limit and offset query parameters when listing certificate bundles.
=> feat(lbaas): certificate bundle paging

upcloud/request/load_balancer.go, upcloud/request/load_balancer_test.go, upcloud/service/fixtures/loadbalancerbackendmember.yaml, upcloud/service/fixtures/loadbalancerfrontendrule.yaml, upcloud/service/load_balancer_test.go, upcloud/utils.go
Use pointers with optional field so that the field can be omitted or alternatively assigned to zero value.
=> fix(lbaas): modification request optional fields

CHANGELOG.md, upcloud/service/fixtures/compresseddirectuploadstorageimport.yaml, upcloud/service/storage.go, upcloud/service/storage_test.go
Set `Content-Type` HTTP header defined in request object.
=> fix(storage): HTTP header when importing storage

CHANGELOG.md, internal/globals.go
- update changelog
- update version string
=> chore: release v4.5.2

CHANGELOG.md, upcloud/request/storage.go, upcloud/request/storage_test.go, upcloud/service/fixtures/createrestorebackup.yaml, upcloud/service/storage_test.go
Possibility to control what to do with backups related to the storage that is about to be deleted using `Backups` field in `DeleteStorageRequest`.
=> feat(storage): delete request parameter `backups`

upcloud/error_codes.go
This just adds error constants for network peerings
=> chore: add network peering err codes

upcloud/error_codes.go
just adds a single missing err code
=> chore: add missing network invalid err code

upcloud/error_codes.go
=> chore: add missing err codes

CHANGELOG.md
Added changes from #227 and #228 to changelog
=> chore(docs): changelog modifications from previous two PRs

upcloud/ip_address.go, upcloud/server.go
Move `IPAddressSlice` into more logical place.
=> chore(upcloud): move IPAddressSlice type into ip_address.go

CHANGELOG.md, upcloud/client/client.go
=> chore: prepare 6.11.0 release

CHANGELOG.md, upcloud/request/server.go, upcloud/request/storage.go, upcloud/request/storage_test.go, upcloud/server_test.go, upcloud/storage.go, upcloud/storage_test.go
=> feat(storage): add support for encryption

CHANGELOG.md, upcloud/client/client.go
=> chore: prepare v8.6.2 release

CHANGELOG.md, upcloud/load_balancer.go, upcloud/load_balancer_test.go, upcloud/request/load_balancer_helpers.go
=> feat(lbaas): add support for new rule actions and matchers

.pre-commit-config.yaml, CHANGELOG.md, upcloud/partner.go, upcloud/partner_test.go, upcloud/request/partner.go, upcloud/request/partner_test.go, upcloud/service/fixtures/createpartneraccount.yaml, upcloud/service/partner.go, upcloud/service/partner_test.go, upcloud/service/service.go
Add support for [Partner API](https://developers.upcloud.com/1.3/23-partner-api/).
=> feat(partner): add Partner API support

upcloud/client/client.go, upcloud/client/client_test.go
Adds a new client constructor `NewFromEnv` that initializes the client using credentials from environment variables:
- UPCLOUD_TOKEN for bearer token authentication.
- UPCLOUD_USERNAME and UPCLOUD_PASSWORD for basic auth.
The constructor validates that only one authentication method's variables are provided and returns an error if both or none are set.
Also includes corresponding unit tests for `NewFromEnv`, utilizing `t.Setenv` for managing environment variables within test cases to ensure proper isolation.
=> feat: Add NewFromEnv client constructor

CHANGELOG.md, upcloud/client/client.go
Added changelog entries from #364 and #365 while at it.
=> chore: prepare release v8.19.0

upcloud/service/utils_test.go
See individual commits for details.
=> test: recorder filtering improvements

CHANGELOG.md, upcloud/client/client.go
=> chore: prepare release v8.22.0

.golangci.yaml, upcloud/client/client.go, upcloud/managed_database.go, upcloud/object_storage.go, upcloud/request/managed_database.go, upcloud/request/network.go, upcloud/request/page.go, upcloud/service/kubernetes.go, upcloud/service/load_balancer_test.go, upcloud/service/managed_database_test.go, upcloud/service/retry_test.go, upcloud/service/tag.go, upcloud/storage.go
See individual commits for details.
=> refactor: trivial linter fixups and tightenings
